
spring:
  application:
    name: springcloud-config-server
  #profiles:
    #active: online
    #active: dev

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiangfumei/cloud
          #search-paths: /api/**   #表示只要访问以/api/开头的多层目录都可以路由到 id为client的服务上
          search-paths: respo
          username: jiangfumei    #如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写，本例子是公开仓库，放心使用。
          password: jfm19961106
          clone-on-start: true #开启启动时直接从git获取配置
          default-label: master

server:
  port: 3990

eureka:
  client:
    register-with-eureka: true  #注册到Eureka的注册中心
    fetch-registry: true  #获取注册实例列表
    serviceUrl:
      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true