
spring:
  application:
    name: cloud-config
  #profiles:
    #active: online
    #active: dev

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiangfumei/cloud
          search-paths: /api/**   #表示只要访问以/api/开头的多层目录都可以路由到 id为client的服务上
          username: jiangfumei
          password: jfm19961106
          clone-on-start: true #开启启动时直接从git获取配置
          default-label: master

server:
  port: 7990

eureka:
  client:
    register-with-eureka: true  #注册到Eureka的注册中心
    fetch-registry: true  #获取注册实例列表
    serviceUrl:
      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true