
spring:
  application:
    name: springcloud-ribbon-client

server:
  port: 5990

eureka:
  client:
    register-with-eureka: true  #注册到Eureka的注册中心
    fetch-registry: true  #获取注册实例列表
    serviceUrl:
      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true

