
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/go-one?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: jfm
    driverClassName: com.mysql.jdbc.Driver

  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3s
    maxTotal: 500
    maxWaitMillis: 5000
    maxIdle: 50