
spring:
  datasource:
    url: jdbc:mysql://192.168.1.246:4306/go-one?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

  redis:
    database: 6
    host: 192.168.1.246
    port: 6379
    password:
    timeout: 3s
    maxTotal: 500
    maxWaitMillis: 5000
    maxIdle: 50