spring:
  application:
    name: eureka-zuul
server:
  port: 4999
eureka:
  client:
    service-url: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumer-ribbon
    api-b:
      path: /api-b/**
      serviceId: consumer-feign