
spring:
  application:
    name: springcloud-consumer-feign

server:
  port: 6990

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true