
spring:
  application:
    name: eureka-client

server:
  port: 8990

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true

#zuul:
  #routes:
    #feign-auth:
      #path: /auth/**
      #serviceId: crawler-auth
      #strip-prefix: true
      #custom-sensitive-headers: true
    #feign-user:
      #path: /user/**
      #serviceId: crawler-goddess
      #sensitiveHeaders: