

spring:
  application:
    name: springcloud-hystrix-dashboard

server:
  port: 7999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true

