

spring:
  application:
    name: springcloud-hystrix-dashboard

server:
  port: 3990

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true

